/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-cuda_buffer
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_CUDA_BUFFER_API_H
#define INCLUDED_CUDA_BUFFER_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_cuda_buffer_EXPORTS
#define CUDA_BUFFER_API __GR_ATTR_EXPORT
#else
#define CUDA_BUFFER_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_CUDA_BUFFER_API_H */
